label Vicharak Axon Linux
  kernel /boot/Image
  devicetree /boot/rk3588-axon-linux.dtb
  append root=PARTLABEL=rootfs earlycon rootwait

setenv bootargs console=ttyS9,1500000 earlyprintk root=/dev/mmcblk0p2 rootwait
